
flags: {}

packages:
 - haskell/concurrent-skiplist/
 - haskell/lvish/
 - haskell/par-classes/
 - haskell/par-collections/
 - haskell/par-collections/tests/
 - haskell/par-mergesort/
 - haskell/par-transformers/

# TODO: Revive:
 # - haskell/lvish-apps/
 # - haskell/lvish-apps/cfa/
 # - haskell/lvish-apps/pbbs/
# - haskell/lvish-graph-algorithms/
 # - haskell/fhpc13-lvars/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-LVar/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-monad-par/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-Strategies/


extra-deps:
 - atomic-primops-0.8
 - chaselev-deque-0.5.0.5
 - bits-atomic-0.1.3
 - thread-local-storage-0.1.0.3

resolver: lts-2.19
