flags: {}
packages:
- src/lvish/
- src/par-classes/
- src/par-collections/
- src/par-collections/tests/
- src/par-mergesort/
- src/par-transformers/
- deps/concurrent-skiplist/
- deps/ctrie
- location:
    git: https://github.com/iu-parfunc/tslogger.git
    commit: bfa8d2b52f0d41439863b15863baa0ca2ef613d9
  extra-dep: true
- location:
    git: https://github.com/iu-parfunc/verified-instances.git
    commit: 6043c1335699d22c514274b9d18d8e9dd6501bc9
  extra-dep: true
extra-deps:
- chaselev-deque-0.5.0.5
- constraints-0.8
- ctrie-0.1.0.3
- pcg-random-0.1.3.4
- rdtsc-1.3.0.1
- test-framework-quickcheck2-0.3.0.4
- thread-local-storage-0.1.0.3
resolver: lts-8.9
