
# flags: {}

packages:
 - src/lvish/
 - src/par-classes/
 - src/par-collections/
 - src/par-collections/tests/
 - src/par-mergesort/
 - src/par-transformers/
 - deps/concurrent-skiplist/
 - deps/ctrie

 - location:
    git:  https://github.com/iu-parfunc/tslogger.git
    commit: f4036354ca9c56c127bcbdeb5498db5b4893c10b
    
# TODO: Revive:
 # - haskell/lvish-apps/
 # - haskell/lvish-apps/cfa/
 # - haskell/lvish-apps/pbbs/
# - haskell/lvish-graph-algorithms/
 # - haskell/fhpc13-lvars/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-LVar/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-monad-par/
 # - haskell/fhpc13-lvars/benchmarks/bf-traverse-Strategies/

# TODO: Add:
# haskell/par-schedulers
 
extra-deps:
# Soon:  
# - tslogger-0.1.0.1
 - atomic-primops-0.8.0.3
 - chaselev-deque-0.5.0.5
 - bits-atomic-0.1.3
 - thread-local-storage-0.1.0.3
 - pcg-random-0.1.3.4
 
resolver: lts-6.8
