flags: {}
packages:
- src/lvish/
- src/par-classes/
- src/par-collections/
- src/par-collections/tests/
- src/par-mergesort/
- src/par-transformers/
- deps/concurrent-skiplist/
- deps/ctrie/
- location:
    git: https://github.com/iu-parfunc/tslogger.git
    commit: bfa8d2b52f0d41439863b15863baa0ca2ef613d9
  extra-dep: true
- ../statefulness
- ../ohua-core
extra-deps:
- chaselev-deque-0.5.0.5
- pcg-random-0.1.3.4
- thread-local-storage-0.1.0.3
#- tslogger-0.2.1.0
- rdtsc-1.3.0.1
resolver: lts-6.13
