flags: {}

packages:
 - '.'
 - '../par-classes'
 - '../par-collections'
 - '../concurrent-skiplist'

extra-deps:
 - bits-atomic-0.1.3
 - chaselev-deque-0.5.0.5
 - thread-local-storage-0.1.0.3

resolver: lts-4.2
